#!/bin/bash

export VEHNAME="<YOUR_DUCKIEBOT_NAME>"

# NOTE: before running make sure that all the old containers from the images dt-duckiebot-interface, dt-car-interface
#       and dt-core are stopped.

# Run demo_all_drivers
dts duckiebot demo --demo_name all_drivers --duckiebot_name $VEHNAME --package_name duckiebot_interface --image duckietown/dt-duckiebot-interface:daffy

# Run demo_all
dts duckiebot demo --demo_name all --duckiebot_name $VEHNAME --package_name car_interface --image duckietown/dt-car-interface:daffy

#Run joystick 
dts duckiebot keyboard_control $VEHNAME --base_image duckietown/dt-core:daffy-amd64
